print("WELCOME TO MADLIBS")
adj1 = input("Enter an adjective: ")
adj2 = input("Enter another adjective: ")
bird = input("Enter a bird: ")
room = input("Enter a room: ")
past_verb = input("Enter a past tense verb: ")
verb = input("Enter a verb: ")
name = input("Enter a name: ")
noun = input("Enter a noun: ")
liquid = input("Enter a liquid: ")
ing_verb = input("Enter a verb ending in -ing: ")
body_part = input("Enter a body part: ")
plural_noun = input("Enter a plural noun: ")
ing_verb2 = input("Enter a verb ending in -ing: ")
noun2 = input("Enter a noun: ")


print("It was a " + adj1 + ", cold November day.")
print("I woke up to the " + adj2 + " smell of " + bird + " roasting in the " + room + " downstairs.")
print("I " + past_verb + " down the stairs to see if I could help " + verb + " the dinner.")
print("My mom said, \"See if " + name + " need a fresh " + noun + ".\"")
print("So I carried a tray of glasses full of " + liquid + " into the " + ing_verb + " room.")
print("When I got there, I couldn't belive my " + body_part + "!")
print("There were " + plural_noun + " " + ing_verb2 + " on the " + noun2 + ".")